# Site settings
title: Pecker
email: hafiz@wehavefaces.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pecker" # the subpath of your site, e.g. /blog/
url: "http://wehavefaces.net" # the base hostname & protocol for your site
twitter_username: sogko
github_username:  sogko

# Build settings
markdown: kramdown
